import os
import re
import subprocess
import random

def get_video_dimensions(video_path: str, log_callback) -> tuple[int, int] | None:
    # (Unchanged from previous version)
    command = [
        "ffprobe", "-v", "error", "-select_streams", "v:0",
        "-show_entries", "stream=width,height", "-of", "csv=s=x:p=0", video_path
    ]
    try:
        result = subprocess.run(command, capture_output=True, text=True, check=True)
        w, h = map(int, result.stdout.strip().split('x'))
        return w, h
    except Exception as e:
        log_callback(f"  Error getting video dimensions: {e}")
        return None

def parse_timestamp_to_seconds(timestamp_str: str, log_callback) -> float:
    # (Unchanged from previous version)
    try:
        parts = timestamp_str.split(':')
        if len(parts) == 3:
            h, m, s = map(float, parts)
            return h * 3600 + m * 60 + s
        elif len(parts) == 2:
            m, s = map(float, parts)
            return m * 60 + s
        return float(parts[0])
    except (ValueError, IndexError):
        log_callback(f"  Error: Invalid timestamp format '{timestamp_str}'.")
        return 0.0

def format_time_ass(seconds: float) -> str:
    # (Unchanged from previous version)
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    cs = int((seconds - int(seconds)) * 100)
    return f"{h:01}:{m:02}:{s:02}.{cs:02}"

def generate_subtitles_ass(transcription_data: dict, start_sec: float, end_sec: float, subtitle_options: dict, log_callback) -> str | None:
    """Generates dynamic ASS subtitle content based on user-defined styles."""
    if not transcription_data or "segments" not in transcription_data:
        log_callback("  Warning: Word-level transcription data not found. Cannot generate subtitles.")
        return None

    # --- Style Mapping from UI Options ---
    font = subtitle_options.get("font", "Impact")
    font_size = int(subtitle_options.get("font_size", 60))
    position = subtitle_options.get("position", "Inferior")
    color_theme = subtitle_options.get("color_theme", "Yellow/White")
    animation_style = subtitle_options.get("animation_style", "Elastic-Jump")
    outline_thickness = int(subtitle_options.get("outline_thickness", 3))
    shadow_depth = int(subtitle_options.get("shadow_depth", 3))
    remove_punctuation = subtitle_options.get("remove_punctuation", True) # Get the flag

    # --- Punctuation Regex ---
    punctuation_re = re.compile(r"[.,!?;:]+")

    color_map = {
        "Yellow/White": {"primary": "&H00FFFFFF", "highlight": "&H0000FFFF"},
        "Green/White": {"primary": "&H00FFFFFF", "highlight": "&H0000FF00"},
        "Red/White": {"primary": "&H00FFFFFF", "highlight": "&H000000FF"},
        "Neon Blue/White": {"primary": "&H00FFFFFF", "highlight": "&H00FFD700"}
    }
    primary_color = color_map.get(color_theme, {}).get("primary", "&H00FFFFFF")
    highlight_color = color_map.get(color_theme, {}).get("highlight", "&H0000FFFF")

    # --- Position Mapping (Alignment and Margin) ---
    pos_map = {
        "Inferior":       {"align": 2, "marginV": 30},
        "Meio-Inferior":  {"align": 2, "marginV": 175},
        "Centralizado":     {"align": 5, "marginV": 30},
        "Meio-Superior":  {"align": 8, "marginV": 150},
        "Superior":       {"align": 8, "marginV": 30}
    }
    alignment = pos_map.get(position, {}).get("align", 2)
    margin_v = pos_map.get(position, {}).get("marginV", 30)

    # --- ASS Header and Dynamic Styles ---
    ass_header = f"""
[Script Info]
Title: Generated by Gemini Shorts Automator
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1080
PlayResY: 1920
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Normal,{font},{font_size},{primary_color},&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,{outline_thickness},{shadow_depth},{alignment},10,10,{margin_v},1
Style: Highlight,{font},{font_size + 5},{highlight_color},&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,{outline_thickness},{shadow_depth},{alignment},10,10,{margin_v},1
Style: Impact,{font},{font_size + 10},{highlight_color},&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,{outline_thickness + 1},{shadow_depth + 1},{alignment},10,10,{margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

    events = []
    
    # Iterate over segments and then words within each segment
    for segment in transcription_data.get("segments", []) :
        for word_info in segment.get("words", []) :
            # Filter words within the highlight's time range
            if not (word_info.get('start', -1) >= start_sec and word_info.get('end', -1) <= end_sec):
                continue

            start_time = word_info['start'] - start_sec
            end_time = word_info['end'] - start_sec
            start_str = format_time_ass(start_time)
            end_str = format_time_ass(end_time)

            style = word_info.get("style", "normal").capitalize()
            text = word_info.get("word", "")
            
            # --- Punctuation and Case Removal ---
            if remove_punctuation:
                text = punctuation_re.sub("", text).lower()

            if "emoji" in word_info:
                text += " " + word_info["emoji"]

            # Apply animation based on style tag and user choice
            if style == "Impact":
                if animation_style == "Elastic-Jump":
                    # Bounces in with a slight elastic effect
                    text = f"{{{{\an5\t(0, 100, \fscx120\fscy120)\t(100, 400, \fscx115\fscy115)}}}}{text}"
            
            events.append(f"Dialogue: 0,{start_str},{end_str},{style},,0,0,0,,{text}")

    return ass_header + "\n".join(events)

def reformat_video_for_output(original_width: int, original_height: int, output_format: str, log_callback) -> str:
    # (Unchanged from previous version)
    filters = []
    if output_format == 'shorts_vertical':
        target_w, target_h = 1080, 1920
    elif output_format == 'square':
        target_w, target_h = 1080, 1080
    else:
        return ""

    original_aspect = original_width / original_height
    target_aspect = target_w / target_h

    if original_aspect > target_aspect:
        scale_h = target_h
        scale_w = int(scale_h * original_aspect)
    else:
        scale_w = target_w
        scale_h = int(scale_w / original_aspect)
    
    filters.append(f"scale={scale_w}:{scale_h}")
    filters.append(f"crop={target_w}:{target_h}")
    return ",".join(filters)

def cut_and_reformat_video(original_video_path: str, highlights_data: list, output_dir: str, output_format: str, log_callback, transcription_data: dict = None, subtitle_options: dict = None, music_options: dict = None):
    """Cuts video segments, adds dynamic subtitles, reformats, adds background music, and saves."""
    log_callback(f"  Starting video processing for {os.path.basename(original_video_path)}...")
    os.makedirs(output_dir, exist_ok=True)

    dims = get_video_dimensions(original_video_path, log_callback)
    if not dims:
        log_callback(f"  Error: Could not get dimensions for {original_video_path}. Skipping.")
        return

    # --- Background Music Setup ---
    music_file_path = None
    if music_options and music_options.get("enabled"):
        music_folder = music_options.get("folder")
        if music_folder and os.path.isdir(music_folder):
            try:
                supported_formats = ('.mp3', '.wav', '.aac', '.flac', '.ogg', '.m4a')
                music_files = [os.path.join(music_folder, f) for f in os.listdir(music_folder) if f.lower().endswith(supported_formats)]
                if music_files:
                    music_file_path = random.choice(music_files)
                    log_callback(f"    Selected background music: {os.path.basename(music_file_path)}")
                else:
                    log_callback("    Warning: No supported audio files found in the specified music folder.")
            except Exception as e:
                log_callback(f"    Warning: Could not select music file. Error: {e}")
        else:
            log_callback("    Warning: Music folder not specified or not found. No background music will be added.")


    for i, highlight in enumerate(highlights_data):
        subtitle_file_path = None
        try:
            start_sec = parse_timestamp_to_seconds(highlight['start_time'], log_callback)
            end_sec = parse_timestamp_to_seconds(highlight['end_time'], log_callback)
            duration = end_sec - start_sec
            title = highlight['title']
            
            sanitized_title = re.sub(r'[^\w\s-]', '', title).strip().replace(' ', '_')
            output_filename = f"{sanitized_title}_{i+1}.mp4"
            output_path = os.path.join(output_dir, output_filename)

            log_callback(f"    Processing highlight: '{title}' ({highlight['start_time']} - {highlight['end_time']})")

            # --- Base Command ---
            command = ["ffmpeg", "-y", "-ss", str(start_sec), "-to", str(end_sec), "-i", original_video_path]
            
            # --- Inputs and Filter Complex ---
            video_filters = reformat_video_for_output(dims[0], dims[1], output_format, log_callback)
            audio_filters = []
            input_streams = ["[0:v]"]
            output_maps = []

            # --- Subtitle Filter ---
            if subtitle_options and subtitle_options.get("add_subtitles") and transcription_data:
                log_callback("      Generating dynamic subtitles...")
                ass_content = generate_subtitles_ass(transcription_data, start_sec, end_sec, subtitle_options, log_callback)
                if ass_content:
                    subtitle_file_path = os.path.join(output_dir, f"temp_subs_{i}.ass")
                    with open(subtitle_file_path, "w", encoding="utf-8") as f:
                        f.write(ass_content)
                    
                    escaped_path = subtitle_file_path.replace('\\', '/').replace(':', '\\:')
                    subtitle_filter = f"subtitles='{escaped_path}'"
                    video_filters = f"{video_filters},{subtitle_filter}" if video_filters else subtitle_filter

            # --- Music Filter ---
            if music_file_path:
                command.extend(["-stream_loop", "-1", "-i", music_file_path])
                music_volume = music_options.get("volume", 0.2)
                # Input 0 is video, Input 1 is music
                audio_filters.append(f"[0:a]volume=1[a0]")
                audio_filters.append(f"[1:a]volume={music_volume}[a1]")
                audio_filters.append(f"[a0][a1]amix=inputs=2:duration=first:dropout_transition=3[a_out]")
                output_maps.extend(["-map", "[v_out]", "-map", "[a_out]"])
            else:
                # If no music, just map the original audio
                output_maps.extend(["-map", "0:v", "-map", "0:a?"])

            # --- Combine Video and Audio Filters ---
            if audio_filters: # If there are audio filters, we must use filter_complex
                final_video_filter = f"{video_filters}[v_out]" if video_filters else "[0:v]null[v_out]"
                filter_complex = ";".join([final_video_filter] + audio_filters)
                command.extend(["-filter_complex", filter_complex])
            elif video_filters: # Only video filters
                command.extend(["-vf", video_filters])

            command.extend(output_maps)

            # --- Output Settings ---
            command.extend([
                "-c:v", "libx264", "-preset", "medium", "-crf", "23",
                "-c:a", "aac", "-b:a", "192k",
                "-t", str(duration), # Use duration for the final output
                output_path
            ])

            log_callback(f"      Executing FFmpeg command: {' '.join(command)}")
            process = subprocess.run(command, capture_output=True, text=True, check=False, encoding='utf-8')

            if process.returncode == 0:
                log_callback(f"    Saved: {output_path}")
            else:
                log_callback(f"    FFmpeg Error for '{title}':\n{process.stderr}")

        except Exception as e:
            log_callback(f"    Error processing highlight '{title}': {e}")
        finally:
            if subtitle_file_path and os.path.exists(subtitle_file_path):
                os.remove(subtitle_file_path)
    
    log_callback("  Finished processing all highlights.")